services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - java-backend
      - python-backend
    networks:
      - app-network

  java-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
      
    env_file:
      - .env

    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}  # Securely pass the GitHub token
    networks:
      - app-network

  python-backend:
    build:
      context: ./backend/python-backend
      dockerfile: Dockerfile
    ports:
      - "5005:5005"  
    networks:
      - app-network
  
  code-comment-coverage:
    build:
      context: ./backend
      dockerfile: ./python-backend/code-comment/Dockerfile
    ports:
      - "5006:5006"  
    networks:
      - app-network
    volumes:
      - shared-repos:/shared/repos
      
  fan-in-fan-out-api:
    build:
      context: ./backend/python-backend/fan-in-fan-out/api_gateway
      dockerfile: src/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - fan-in-service
      - fan-out-service
    networks:
      - app-network

  fan-in-service:
    build:
      context: ./backend/python-backend/fan-in-fan-out/fan_in_service
      dockerfile: src/Dockerfile
    ports:
      - "8001:8001"
    networks:
      - app-network

  fan-out-service:
    build:
      context: ./backend/python-backend/fan-in-fan-out/fan_out_service
      dockerfile: src/Dockerfile
    ports:
      - "8002:8002"
    networks:
      - app-network
  github-service:
    build:
      context: ./backend/python-backend/fan-in-fan-out/GitHub_service
      dockerfile: src/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    networks:
      - app-network
  
  test-coverage-service:
    build:
      context: ./backend/python-backend/test_coverage
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    networks:
      - app-network
    volumes:
      - ${HOME}/Downloads:/downloads
  
  clone_repo:
      build:
        context: ../
        dockerfile: DockerfileMiddleware
      ports:
        - "6000:6000"
      volumes:
        - shared-repos:/shared/repos
      networks:
        - app-network

  defects-triaged:
    build:
      context: ./backend/python-backend/defects-triaged
      dockerfile: Dockerfile
    ports:
        - "5000:5000"
    environment:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    networks:
        - app-network

networks:
  app-network:
    driver: bridge

volumes:
  shared-repos: