version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - java-backend
      - python-backend
    networks:
      - app-network

  java-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}  # Securely pass the GitHub token
    networks:
      - app-network

  python-backend:
    build:
      context: ./backend/python-backend
      dockerfile: Dockerfile
    ports:
      - "5005:5005"  
    networks:
      - app-network
  
  code-comment-coverage-backend:
    build:
      context: ./backend/python-backend/code-comment
      dockerfile: Dockerfile
    ports:
      - "5006:5006"  
    networks:
      - app-network
      
  fan-in-fan-out-api:
    build:
      context: ./backend/python-backend/fan-in-fan-out/api_gateway
      dockerfile: src/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - fan-in-service
      - fan-out-service
    networks:
      - app-network

  fan-in-service:
    build:
      context: ./backend/python-backend/fan-in-fan-out/fan_in_service
      dockerfile: src/Dockerfile
    ports:
      - "8001:8001"
    networks:
      - app-network

  fan-out-service:
    build:
      context: ./backend/python-backend/fan-in-fan-out/fan_out_service
      dockerfile: src/Dockerfile
    ports:
      - "8002:8002"
    networks:
      - app-network
  github-service:
    build:
      context: ./backend/python-backend/fan-in-fan-out/GitHub_service
      dockerfile: src/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge