name: CI/CD Pipeline

on:
  push:
    branches:
      - Period-3
      - dev
  pull_request:
    branches:
      - Period-3
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and Tag Docker Images
        run: |
          docker build -t app-python-backend ./app/backend/python-backend
          docker build -t app-java-backend ./app/backend
          docker build -t app-frontend ./app/frontend
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          echo "${{ secrets.DOCKER_PASSWORD }}"
      
      - name: Tag and push images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker tag app-python-backend mkapure/app-python-backend:latest
          docker tag app-java-backend mkapure/app-java-backend:latest
          docker tag app-frontend mkapure/app-frontend:latest
          
          docker push mkapure/app-python-backend:latest
          docker push mkapure/app-java-backend:latest
          docker push mkapure/app-frontend:latest
